org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
org.gradle.parallel=true

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.95
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Mod Properties
mod_version=1.0.7
mod_id=fiw_bosses
mod_name=FIW Bosses
mod_license=All Rights Reserved
mod_group_id=com.fiw
mod_authors=fi3w0
mod_description=Configurable bosses with phases, abilities and dialogue.

maven_group=com.fiw
archives_base_name=fiw-bosses-neoforge-1.21.1
