modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-only"
issueTrackerURL="https://github.com/Fi3w0/Fiw-Bosses/issues"

[[mods]]
modId="fiw_bosses"
version="${version}"
displayName="FIW Bosses"
authors="Fi3w0"
logoFile="icon.png"
description='''
Configurable bosses with phases, abilities and dialogue.
'''

[[dependencies.fiw_bosses]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.fiw_bosses]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
